// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"EventLabel","status":true,"description":"イベントラベルプラグイン","parameters":{"showDefault":"false","hideNoImage":"true","hideNameEv":"true","fontSize":"16","backColor":"rgba(0,0,0,0.5)","padding":"2"}},
{"name":"MNKR_CommandPosition","status":true,"description":"メインメニューの表示位置を変更します。","parameters":{"Command Position":"7","Command Rows":"4","Status Window Hide":"true","Gold Window Hide":"true"}},
{"name":"TorigoyaMZ_CommonMenu","status":true,"description":"メニューからコモンイベント呼び出しプラグイン (v.1.1.0)","parameters":{"base":"","baseItems":"[\"{\\\"name\\\":\\\"タイル切り替え\\\",\\\"commonEvent\\\":\\\"3\\\",\\\"switchId\\\":\\\"0\\\",\\\"visibility\\\":\\\"true\\\",\\\"note\\\":\\\"\\\"}\",\"{\\\"name\\\":\\\"前マップに移動\\\",\\\"commonEvent\\\":\\\"2\\\",\\\"switchId\\\":\\\"0\\\",\\\"visibility\\\":\\\"true\\\",\\\"note\\\":\\\"\\\"}\"]"}}
];
